# TODO: Sort this file

PROJECT_NAME = "Temp Name"
MAX_FILE_SIZE = 2 * 1024 * 1024 * 1024  # 2GB
UPLOAD_BATCHES_BUCKET_NAME = "upload_batches"
IMAGES_BUCKET_NAME = "images"
HASHING_BUF_SIZE = 65536
BUCKET_NAME_HASH_ALGORITHM = "sha256"
UPLOAD_INTEGRITY_HASH_ALGORITHM = "md5"
ALLOWED_IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png"}
DEFAULT_PROCESSING_TIME = 100
TEMPLATES_PATH = "web/templates"
