# TODO: Sort this file
import os

from dotenv import load_dotenv
from PIL import Image

PROJECT_NAME = "Barbell"
PROJECT_URL = "example.com"
PROJECT_VERSION = "0.0.1"
MAX_FILE_SIZE = 2 * 1024 * 1024 * 1024  # 2GB
UPLOAD_BATCHES_BUCKET_NAME = "upload_batches"
DOWNLOAD_BATCHES_BUCKET_NAME = "download_batches"
IMAGES_BUCKET_NAME = "images"
HASHING_BUF_SIZE = 65536
BUCKET_NAME_HASH_ALGORITHM = "sha256"
UPLOAD_INTEGRITY_HASH_ALGORITHM = "md5"
ALLOWED_IMAGE_EXTENSIONS = {ex for ex, f in Image.registered_extensions().items() if f in Image.OPEN}
IMAGE_STORAGE_FORMAT = "png"
DEFAULT_PROCESSING_TIME = 100
TEMPLATES_PATH = "web/templates"
SECURE_ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 30
MAX_USERNAME_LEN = 50
MIN_USERNAME_LEN = 3
MAX_PASSWORD_LENGTH = 128
MIN_PASSWORD_LENGTH = 6
MAX_TEAM_NAME_LEN = 128
MAX_TEAM_NUMB = 99999
SMTP_URL = "mailpit"
SMTP_PORT = 1025
APP_EMAIL_ADDRESS = "testing@example.com"
VERIFICATION_CODE_STR_LEN = 24
VERIFICATION_CODE_BYTES_LEN = 16
API_KEY_LEN = 16
MAX_DOWNLOAD_COUNT = 10000
DOWNLOAD_BATCH_SAVE_DISTANCE = 5
IS_PRODUCTION = False

load_dotenv()
JWT_SECRET_TOKEN = os.getenv("JWT_SECRET_KEY")
DATABASE_URL = os.getenv("DATABASE_URL")
